seafarer/agency/urls.py
from django.urls import path

from . import views

app_name = 'agency'
urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('crew/add', views.crew_add, name='crew_add'),
    path('ships/add', views.ships_add, name='ships_add'),
    path('analytics', views.analytics, name='analytics'),
    path('apply', views.apply, name='apply'),
    path('test', views.test, name='test'),
]

seafarer/seafarer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('agency/', include('agency.urls')),
    path('admin/', admin.site.urls),
]

seafarer/agency/forms.py
from django.forms import ModelForm
from .models import Crew, Ship, Charter

class CrewCreationForm(ModelForm):
    class Meta:
        model = Crew
        fields = ['first_name', 'last_name', 'middle_name',
                  'phone', 'email', 'sex', 'birth_date', 'address', 'country_of_residence',
                  'position'
        ]

class ShipCreationForm(ModelForm):
    class Meta:
        model = Ship
        fields = ['name', 'speed_class', 'IMO', 'vessel_type',
                 'status', 'call_sign', 'flag', 'gross_tonnage',
                 'summer_dwt', 'length_overall', 'breadth_extreme',
                 'year_built', 'home_port']

class CharterCreationForm(ModelForm):
    class Meta:
        model = Charter
        exclude = ['to_datetime']

seafarer/agency/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.http import require_http_methods
from django.urls import reverse
from seafarer import settings
from .utils import send_email, generate_confirmation_token, confirm_token
from .models import Crew, Ship, Charter
from .forms import CrewCreationForm, ShipCreationForm, CharterCreationForm
import json



def test(request):
    form = CharterCreationForm()
    return render(request, 'agency/test.html', {'form':form})

def dashboard(request):
    context = {
        'page_name': 'Dashboard'
    }
    return render(request, 'agency/dashboard.html', context)


def crew_add(request):
    context = {
        'page_name': 'Crew',
    }
    if request.method == 'POST':
        form = CrewCreationForm(request.POST)
        if form.is_valid():
            new_crew = form.save()
            return HttpResponseRedirect(reverse('agency:crew_add'))
    else:
        form = CrewCreationForm()
    context['form'] = form
    return render(request, 'agency/crew_add.html', context)

def crew_manage(request):
    context = {
        'page_name': 'Crew',
    }
    crews = Crew.objects.all()
    context['crews'] = crews
    return render(request, 'agency/crew_manage.html', context)

def crew_manage_one(request, pk):
    context = {
        'page_name': 'Crew',
    }
    crew = get_object_or_404(Crew, pk=pk)
    form = CrewCreationForm(instance=crew)
    context['form'] = form
    return render(request, 'agency/crew_manage_one.html', context)

@require_http_methods(['POST'])
def crew_edit(request, pk):
    context = {
        'page_name': 'Crew',
    }
    form = CrewCreationForm(request.POST)
    if form.is_valid():
        new_crew = form.save()
        return HttpResponseRedirect(reverse('agency:crew_manage'))
    else:
        context['form'] = form
        return render(request, 'agency/crew_manage.html', context)

def charters_delete(request, pk):
    context = {

        'page_name': 'Charters',
        'form': CharterCreationForm()
    }
    crew = get_object_or_404(Crew, pk=pk)
    context['crew'] = crew
    return render(request, 'agency/crew_delete.html', context)

@require_http_methods(['POST'])
def charter_create(request):
    form = CharterCreationForm(request.POST)
    if form.is_valid():
        new_charter = form.save()
        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'failed', 'errors': form.errors})

def ships_add(request):
    if request.method == 'POST':
        print('post')
    context = {
        'page_name': 'Ships',
        'form': ShipCreationForm()
    }
    return render(request, 'agency/ships.html', context)

@require_http_methods(['POST'])
def ship_create(request):
    form = ShipCreationForm(request.POST)
    if form.is_valid():
        new_ship = form.save()
        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'failed', 'errors': form.errors})

def analytics(request):
    context = {
        'page_name': 'Analytics'
    }
    return render(request, 'agency/analytics.html', context)


def apply(request):
    context = {
        'page_name': 'Apply'
    }
    return render(request, 'agency/apply.html', context)

seafarer/agency/templates/agency/admin_template.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Allison&display=swap" rel="stylesheet">
        <!-- Animation -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
        
        <title>{{ page_name }} | Seafarer International</title>
    </head>
        <style>
            .menu-item-modal {
                cursor: pointer;
            }
            .menu-item-modal:hover {
                color: rgb(89, 17, 122);
            }

            .purple-gradient {
            background: -webkit-linear-gradient(#4432ba, #462f66);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            }

            body {
                background-color: #f8f8fa !important; 
            }

            /* input::-webkit-calendar-picker-indicator{
                display: none;
            } */

            img {
                pointer-events: none;
            }

            *:not(i) {
                font-family: 'Manrope', sans-serif !important;
            }

            .name-app {
                font-size: 0.75rem;
            }

            #regular-sidebar {
                margin: 0 !important;
                height: 100% !important;
                width: 280px !important;
                overflow-y: auto;
                position: fixed;
            }

            #block-content {
                width: 100%;
                padding: 4vw;
                flex: 1;
                margin: 0 0 0 280px;
            }

            .form-control:focus {
                border-color: #52acd6;
                box-shadow: none;
            }

            .btn-close:focus {
                box-shadow: none;
            }

            .btn:focus {
                border-color: transparent !important;
                filter: brightness(80%);
                box-shadow: none !important;
            }

            .form-select:focus {
                border-color: #52acd6;
                box-shadow: none;
            }

            

            .nav-link.link-dark {
                padding-top: 12px;
                padding-bottom: 12px;
                color: rgb(54, 54, 54);
            }

            #regular-sidebar a {
                border-radius: 15px !important;
                cursor: pointer;
            }

            #regular-sidebar a:hover {
                border-radius: 15px !important;
                background: none !important;
                background-color: rgb(235, 235, 235) !important;
                color: rgb(63, 63, 63) !important;
            }

            #scan_qr_img:hover {
                filter: brightness(170%);
                transition: 0.15s ease-in;
            }

            .card {
                border-radius: 20px; 
                border: none; 
                box-shadow: 1px 2px 9px 1px rgba(0,0,0,0.05);
                -webkit-box-shadow: 1px 2px 9px 1px rgba(0,0,0,0.05);
                -moz-box-shadow: 1px 2px 9px 1px rgba(0,0,0,0.05);
                background-color: #ffffff;
                display: block;
            }

            .card .header-content {
                font-size: 1.2rem;
            }

            .card .sub-content {
                font-size: 0.9rem;
            }

            .card .div-cover {
                height: 150px;
            }

            .card .card-img-top {
                border-radius: 20px 20px 0 0; 
                width:100%;
                height:100%; 
                object-fit:cover; 
            }

            label {
                font-weight: 600;
                font-size: 0.8rem;
                margin-bottom: 0.2rem !important;
                color: rgb(66, 66, 66);
            }

            .h1, .h2, .h3, .h4, .h5, .h6, th {
                color: rgb(61, 61, 61);
            }

            #no_result i {
                color: rgb(61, 61, 61);
            }

            #nothing_to_see i {
                color: rgb(61, 61, 61);
            }

            #result_table .manage-action {
                width: 85px;
            }

            #edit-btn-manage {
                cursor: pointer;
            }

            #edit-btn-manage:hover {
                color: rgb(133, 133, 133);
            }

            .reveal_detail, .hide_detail {
                cursor: pointer;
            }

            .reveal_detail:hover {
                color: rgb(133, 133, 133);
            }

            .hide_detail:hover {
                color: rgb(133, 133, 133);
            }

            canvas {
                width: 100%;
            }

            .active-menu {
                background-color: transparent !important;
                background: rgb(15,74,115) !important;
                background: linear-gradient(145deg, rgba(15,74,115,1) 29%, rgba(15,145,165,1) 100%) !important;
                color: white !important;
            }

            #qr_focus_modal canvas {
                width: 100%;
                object-fit: contain;
                height: 98%;
            }

            @media (max-width: 1199.98px) { 
                #regular-sidebar {
                    width: 230px !important;
                }

                #block-content {
                    margin: 0 0 0 230px;
                }
            }

            @media (max-width: 991.98px) { 
                #regular-sidebar {
                    height: 100% !important;
                    width: 5.9rem !important;
                    padding: 0 !important;
                    position: fixed;
                    bottom: 0 !important;
                    z-index: 100;
                }

                #regular-sidebar .nav-inner-text {
                    font-size: 7.5px;
                    display: block !important;
                    margin-top: -5px;
                }

                #regular-sidebar ul {
                    flex-direction: column !important;
                    flex: 1;
                    align-items: center !important;
                }

                #regular-sidebar li {
                    flex: 1;
                    margin: 0 !important;
                }

                #regular-sidebar i {
                    font-size: 25px !important;
                }

                #block-content {
                    margin: 0 0 0 5.5rem;
                }

                #regular-sidebar ul {
                    text-align: center;
                }

                #regular-sidebar i {
                    margin: 0 !important;
                }

                .to-hide {
                    display: none !important;
                }

                .active-menu {
                    border-radius: 0 !important;
                    background: none !important;
                    background: rgb(15,74,115);
                    background: linear-gradient(145deg, rgba(15,74,115,1) 29%, rgba(15,145,165,1) 100%);
                    color: white !important;
                }

                #regular-sidebar a:hover {
                    background: none !important;
                    background-color: none !important;
                }
            }

            @media (max-width: 767.98px) { 
                #regular-sidebar {
                    height: 4.5rem !important;
                    width: 100% !important;
                    padding: 0 !important;
                    position: fixed;
                    bottom: 0 !important;
                    z-index: 100;
                    {{menu_elements.app_gradient}}
                }

                #regular-sidebar .nav-inner-text {
                    font-size: 7.5px;
                    display: block !important;
                    margin-top: -5px;
                }


                #regular-sidebar ul {
                    flex-direction: row !important;
                    flex: 1;
                    align-items: center !important;
                }

                #regular-sidebar li {
                    flex: 1;
                    margin: 0 !important;
                }

                #regular-sidebar i {
                    font-size: 25px !important;
                }

                #block-content {
                    margin: 0;
                    padding-bottom: 100px !important;
                }

                #regular-sidebar ul {
                    text-align: center;
                }

                #regular-sidebar i {
                    margin: 0 !important;
                }

                .to-hide {
                    display: none !important;
                }

                .active-menu {
                    border-radius: 0 !important;
                    background: none !important;
                    color: white !important;
                }

                #regular-sidebar a:hover {
                    background: none !important;
                    background-color: none !important;
                }
            }
        </style>

        <div id='wrapper' class="d-flex">
            <div id='regular-sidebar' class="d-flex flex-column flex-shrink-0 p-4 bg-white">
                <img src="{% static 'agency/small_logo.png' %}" class='to-hide mx-auto d-block my-4' width="35%">
                <p class="to-hide name-app fw-bold h6 text-center">Lumanlan, John Bryan</p>
                <p class="to-hide name-app text-center mb-0">Manager</p>
                <hr class="to-hide my-4">
                <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item mb-3" data-bs-toggle="modal" data-bs-target="#menu_modal">
                        <a href='{% url "agency:dashboard" %}' class="nav-link link-dark {% if page_name == 'Dashboard' %}active-menu{%endif%}">
                            <i class="bi bi-columns me-2"></i>
                            <span class='nav-inner-text d-inline-block'> Dashboard</span>
                        </a>
                    </li>


                    <li class="nav-item mb-3" data-bs-toggle="modal" data-bs-target="#menu_modal">
                        <a href='{% url "agency:crew_add" %}' class="nav-link link-dark {% if page_name == 'Crew' %}active-menu{%endif%}">
                            <i class="bi bi-people-fill me-2"></i>
                            <span class='nav-inner-text d-inline-block'> Crew</span>
                        </a>
                    </li>

                    <li class="nav-item mb-3" data-bs-toggle="modal" data-bs-target="#menu_modal">
                        <a href='{% url "agency:charters_add" %}' class="nav-link link-dark {% if page_name == 'Charters' %}active-menu{%endif%}">
                            <i class="bi bi-geo-alt-fill me-2"></i>
                            <span class='nav-inner-text d-inline-block'> Charters</span>
                        </a>
                    </li>

                    <li class="nav-item mb-3" data-bs-toggle="modal" data-bs-target="#menu_modal">
                        <a href='{% url "agency:ships_add" %}' class="nav-link link-dark {% if page_name == 'Ships' %}active-menu{%endif%}">
                            <i class="bi bi-droplet-fill me-2"></i>
                            <span class='nav-inner-text d-inline-block'> Ships</span>
                        </a>
                    </li>

                    <li class="nav-item mb-3" data-bs-toggle="modal" data-bs-target="#menu_modal">
                        <a href='{% url "agency:analytics" %}' class="nav-link link-dark {% if page_name == 'Analytics' %}active-menu{%endif%}">
                            <i class="bi bi-bar-chart-line-fill me-2"></i>
                            <span class='nav-inner-text d-inline-block'> Analytics</span>
                        </a>
                    </li>
                    
                    <li class="nav-item mb-3">
                        <a href='#' class="nav-link link-dark">
                            <i class="bi bi-box-arrow-left me-2"></i>
                            <span class='nav-inner-text d-inline-block'> Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
            <div id='block-alert'>

            </div>
            <div id='block-content'>
                {% block content %}
                {% endblock %}
            </div>
            <div id='block-script'>
            </div>

            
        </div>
     


        <!-- DOMPurify-->
        <script nonce="" src="https://cdn.jsdelivr.net/npm/dompurify@2.3.0/dist/purify.min.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/ushelp/EasyQRCodeJS/dist/easy.qrcode.min.js" ></script>
        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>
    </body>
</html>

seafarer/agency/templates/agency/analytics.html
{% extends "agency/admin_template.html" %}

seafarer/agency/templates/agency/charters.html
{% extends "agency/admin_template.html" %}
{% load widget_tweaks %}



{% block content %}
<p class="h1 fw-bold mb-5">Charter Management</p>
<div class="card p-5">
    <ul class="nav nav-tabs mb-3">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'agency:crew_add' %}">Create Charter</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Manage Charters</a>
        </li>
    </ul>
    <p class="h3">Ship & Route Details</p>
    <div class="row">
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.ship.label}}
            </label>
            {{form.ship|attr:"class:form-select"}}
        </div>

        <div class="col col-12 col-md-6 mb-3">
            <label class="form-label">
                Origin
            </label>
            {{form.from_place|attr:"class:form-select"}}
        </div>
        <div class="col col-12 col-md-6 mb-3">
            <label class="form-label">
                Destination
            </label>
            {{form.to_place|attr:"class:form-select"}}
        </div>

        <div class="col col-12  mb-3">
            <label class="form-label">
                {{form.from_datetime.label}}
            </label>
            {{form.from_datetime|attr:"class:form-control"}}
        </div>

        <div class="col col-12  mb-3">
            <label class="form-label">
                {{form.description.label}}
            </label>
            {{form.description|attr:"class:form-control"}}
        </div>

    </div>


    <hr class="my-3">
    <p class="h3">Designations</p>
    <div class="row">
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.captain.label}}
            </label>
            {{form.captain|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.chief_mate.label}}
            </label>
            {{form.chief_mate|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.second_mate.label}}
            </label>
            {{form.second_mate|attr:"class:form-select"}}
        </div>
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.third_mate.label}}
            </label>
            {{form.third_mate|attr:"class:form-select"}}
        </div>
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.deck_cadet.label}}
            </label>
            {{form.deck_cadet|attr:"class:form-select"}}
        </div>
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.chief_engineer.label}}
            </label>
            {{form.chief_engineer|attr:"class:form-select"}}
        </div>
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.second_engineer.label}}
            </label>
            {{form.second_engineer|attr:"class:form-select"}}
        </div>
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.third_engineer.label}}
            </label>
            {{form.third_engineer|attr:"class:form-select"}}
        </div>
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.fourth_engineer.label}}
            </label>
            {{form.fourth_engineer|attr:"class:form-select"}}
        </div>
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.engine_cadet.label}}
            </label>
            {{form.engine_cadet|attr:"class:form-select"}}
        </div>
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.electrician.label}}
            </label>
            {{form.electrician|attr:"class:form-select"}}
        </div>
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.boatswain.label}}
            </label>
            {{form.boatswain|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.pump_man.label}}
            </label>
            {{form.pump_man|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.able_bodied_seaman.label}}
            </label>
            {{form.able_bodied_seaman|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.ordinary_seaman.label}}
            </label>
            {{form.ordinary_seaman|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.fitter.label}}
            </label>
            {{form.fitter|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.oiler.label}}
            </label>
            {{form.oiler|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.wiper.label}}
            </label>
            {{form.wiper|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.chief_cook.label}}
            </label>
            {{form.chief_cook|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.steward.label}}
            </label>
            {{form.steward|attr:"class:form-select"}}
        </div>

        <div class="col col-12 mb-3">
            <div class="d-flex justify-content-end">
                <button type="button" class="btn btn-success">Create Charter</button>
            </div>
        </div>
   
    
       
    </div>
</div>
{% endblock %}

seafarer/agency/templates/agency/dashboard.html
{% extends "agency/admin_template.html" %}

{% block content %}

{% endblock %}

seafarer/agency/templates/agency/employees.html
{% extends "agency/admin_template.html" %}

seafarer/agency/templates/agency/ships.html
{% extends "agency/admin_template.html" %}
{% load widget_tweaks %}



{% block content %}
<p class="h1 fw-bold mb-5">Ship Management</p>
<form class="card p-5" method="post" action="{% url 'agency:ships_add' %}">
    {%csrf_token%}
    <ul class="nav nav-tabs mb-3">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'agency:ships_add' %}">Register Ship</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Manage Ships</a>
        </li>
    </ul>
    <p class="h3">Ship Details</p>
    <div class="row">
        <div class="col col-12 mb-3">
            <label class="form-label">
                {{form.name.label}}
            </label>
            {{form.name|attr:"class:form-control"}}
        </div>

        <div class="col col-12 col-md-4 mb-3">
            <label class="form-label">
                {{form.speed_class.label}}
            </label>
            {{form.speed_class|attr:"class:form-select"}}
        </div>
        <div class="col col-12 col-md-4 mb-3">
            <label class="form-label">
                {{form.IMO.label}}
            </label>
            {{form.IMO|attr:"class:form-control"}}
        </div>
        <div class="col col-12 col-md-4 mb-3">
            <label class="form-label">
                {{form.vessel_type.label}}
            </label>
            {{form.vessel_type|attr:"class:form-select"}}
        </div>


        <div class="col col-12 col-md-4 mb-3">
            <label class="form-label">
                {{form.status.label}}
            </label>
            {{form.status|attr:"class:form-select"}}
        </div>
        <div class="col col-12 col-md-4 mb-3">
            <label class="form-label">
                {{form.call_sign.label}}
            </label>
            {{form.call_sign|attr:"class:form-control"}}
        </div>
        <div class="col col-12 col-md-4 mb-3">
            <label class="form-label">
                {{form.flag.label}}
            </label>
            {{form.flag|attr:"class:form-select"}}
        </div>

        <div class="col col-12 col-md-6 mb-3">
            <label class="form-label">
                {{form.gross_tonnage.label}}
            </label>
            {{form.gross_tonnage|attr:"class:form-control"}}
        </div>
        <div class="col col-12 col-md-6 mb-3">
            <label class="form-label">
                {{form.summer_dwt.label}}
            </label>
            {{form.summer_dwt|attr:"class:form-control"}}
        </div>

        <div class="col col-12 col-md-6 mb-3">
            <label class="form-label">
                {{form.length_overall.label}}
            </label>
            {{form.length_overall|attr:"class:form-control"}}
        </div>
        <div class="col col-12 col-md-6 mb-3">
            <label class="form-label">
                {{form.breadth_extreme.label}}
            </label>
            {{form.breadth_extreme|attr:"class:form-control"}}
        </div>

        <div class="col col-12 col-md-6 mb-3">
            <label class="form-label">
                {{form.year_built.label}}
            </label>
            {{form.year_built|attr:"class:form-control"}}
        </div>
        <div class="col col-12 col-md-6 mb-3">
            <label class="form-label">
                {{form.home_port.label}}
            </label>
            {{form.home_port|attr:"class:form-select"}}
        </div>
    
        <div class="col col-12 mb-3">
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-success">Register Ship</button>
            </div>
        </div>
      
       
    </div>
  
</form>
{% endblock %}

seafarer/agency/templates/agency/test.html
{% extends "agency/admin_template.html" %}

{% block content %}
    <form action="/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">

{% endblock %}